# Generated by Django 3.2.7 on 2021-10-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20211030_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
